# Generated by Django 4.2.4 on 2023-08-16 07:04

import django.core.validators
from django.db import migrations, models
import retake.common.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=30)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Sports", "Sports"),
                            ("Festivals", "Festivals"),
                            ("Conferences", "Conferences"),
                            ("Performing Art", "Performing Art"),
                            ("Concerts", "Concerts"),
                            ("Theme Party", "Theme Party"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("date", models.DateField()),
                ("event_image", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="ProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            retake.common.validators.profile_name_must_start_with_a_letter,
                        ],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=30,
                        validators=[django.core.validators.MinLengthValidator(4)],
                    ),
                ),
                ("email", models.EmailField(max_length=45)),
                ("profile_picture", models.URLField(blank=True, null=True)),
                (
                    "password",
                    models.CharField(
                        max_length=20,
                        validators=[django.core.validators.MinLengthValidator(5)],
                    ),
                ),
            ],
        ),
    ]
