# Generated by Django 4.2.4 on 2023-08-16 08:25

import django.core.validators
from django.db import migrations, models
import retake.common.validators


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="password",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.MinLengthValidator(5),
                    retake.common.validators.password_must_contain_at_least_one_digit,
                ],
            ),
        ),
    ]
