# Generated by Django 4.2.4 on 2023-08-16 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_alter_profilemodel_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="first_name",
            field=models.CharField(
                max_length=20, validators=[django.core.validators.MinLengthValidator(2)]
            ),
        ),
        migrations.AlterField(
            model_name="profilemodel",
            name="password",
            field=models.CharField(
                max_length=20, validators=[django.core.validators.MinLengthValidator(5)]
            ),
        ),
    ]
